data_ingestion:
  dataset_url: "https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/refs/heads/master/Datasets/wine.data.csv"
  raw_dataset_dir: "artifacts/data/raw"
  processed_dataset_dir: "artifacts/data/processed"
  dataset_name: "wine.csv"

## data validation

## data transformation
data_transformation:
  dataset_path: "artifacts/data/processed"
  output_dir: "artifacts/data/transformed"
  file_name_train: "train.csv"
  file_name_test: "test.csv"
  features_to_scale:
    - "Alcohol"
    - "Malic acid"
    - "Ash"
    - "Alcalinity of ash"
    - "Total phenols"
    - "Flavanoids"
    - "Nonflavanoid phenols"
    - "Proanthocyanins"
    - "Color intensity"
    - "Hue"
    - "OD280/OD315 of diluted wines"

model_training:
  model: "AdaBoostRegressor"
  learning_rate: 1
  loss: "linear"
  n_estimators: 100
