data_ingestion:
  dataset_url: "https://raw.githubusercontent.com/tirthajyoti/Machine-Learning-with-Python/refs/heads/master/Datasets/wine.data.csv"
  raw_dataset_dir: "artifacts/data/raw"
  processed_dataset_dir: "artifacts/data/processed"
  dataset_name: "wine.csv"

## data validation

## data transformation
data_transformation:
  dataset_path: "artifacts/data/processed"
  output_dir: "artifacts/data/transformed"
  file_name_train: "train.csv"
  file_name_test: "test.csv"
  features_to_scale:
    - "Alcohol"
    - "Malic acid"
    - "Ash"
    - "Alcalinity of ash"
    - "Total phenols"
    - "Flavanoids"
    - "Nonflavanoid phenols"
    - "Proanthocyanins"
    - "Color intensity"
    - "Hue"
    - "OD280/OD315 of diluted wines"

model_training:
  model: "AdaBoostRegressor"
  dataset_path: "artifacts/data/transformed"
  file_name_train: "train.csv"
  file_name_test: "test.csv"
  model_path: "artifacts/model"
  model_name: "AdaBoostRegressor.pkl"
  hyperparameter_file: "hyperparameter.json"
  base_estimator: "DecisionTreeRegressor"
  max_depth: 3
  random_state: 42

model_evaluating:
  test_dir: "artifacts/data/transformed/test.csv"
  model_path: "artifacts/model"
  model_name: "AdaBoostRegressor.pkl"
  metrics_file: "metrics.json"
  tracking-uri: "https://dagshub.com/DevManpreet5/end_end_ML_pipeline.mlflow"
